#!/usr/bin/env bash

# this script runs the flask development server unconditionally for the
# FileStorage environment
echo "Deleting the existing file.json"
rm file.json 2> /dev/null

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <number_of_instances>"
    exit 1
fi

kill_server() {
    echo -e "\nTerminating the server"
    kill -9 "$(pgrep -laf "api.v1.app" | cut -f 1 -d ' ')" 2> /dev/null
}

trap kill_server EXIT

echo "Starting Flask server"
while true; do
    HBNB_API_PORT=5001 python3 -m api.v1.app 2> /dev/null &

    echo "Generating dummy data"
    python ./populate_storage.py "$1"

    sleep 300 # generate more dummy data every five minutes
done
